apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: voe
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: voe
  chart:
    spec:
      chart: ./factory-ai-vision/EdgeSolution/charts/VisionOnEdge
  values:
    azureIoT:
      hubConnectionString: HostName=bx-hub-2.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=W+6h6pZeUVd5DgeLsGtQl7z5IYxxZMcH4MzZtAe2ASM=
      edgeConnectionString: HostName=bx-hub-2.azure-devices.net;DeviceId=bx-0816-p4e;SharedAccessKey=frtpQnyYpRyRqyDaISX8U4FkQAGR1MDBpGpKzhGO+uo=
    customVision:
      endPoint: https://voe-custom-vision-fz7wyvirk67zw.cognitiveservices.azure.com/
      key: 927a44f30a454e5a97bd679682a10c21